### ISSUE TITLE
allow to order fractional units

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#101]
When buying large packages, a foodcoop may want to subdivide it. Currently, that can be done by adjusting the unit, then manually recomputing the unit_quantity and price. This could be much easier when there would be a unit_divide field, indicating in what units members can order.

This is work in progress on branch [uicleanup-new-grouporder-subdivide](https://github.com/foodcoop-adam/foodsoft/tree/uicleanup-new-grouporder-subdivide).
- [x] support non-integer amounts in data model
- [x] include `ruby-units` for unit computations + configure units
- [x] add subdivision to article edit screen
- [x] reintroduce edit boxes in member order screen
- [x] support fractional units in member order screen
- [x] check negative entry in member order @wvengen
- [ ] show price/kg when sensible in member order and admin order screen (using helper) @wvengen
- [ ] unit tests for the use of `unit_divide` (see also foodcoops#120) @tg-x
- [ ] fix any close order and distribute issues
- [ ] integration test(s) for subdivided order @tg-x
- [ ] make balancing screen work (might work already)
- [ ] test that everything (still) really works ok

would be nice / need to do in the future:
- [ ] check that performance doesn't get much worse
- [ ] rebase on upstream (involves some changes)
- [ ] open upstream pull request - see foodcoops#209
- [ ] change confusing [gray box style](https://github.com/foodcoops/foodsoft/issues/209#issuecomment-30059506) of subdivide box in edit article screen
- [ ] use `ruby-units` in `Article#convert_units`

**Comment by wvengen** [comment]
this is mostly done, what remains is finishing unit and integration tests

**Comment by wvengen** [comment]
This is stuck, by the way. May need a data-model redesign (see mails [1](http://foodsoft.51229.x6.nabble.com/Changing-an-article-s-unit-for-subdivision-intermediary-thoughts-with-relationship-diagrams-tp363.html) and [2](http://foodsoft.51229.x6.nabble.com/Re-Article-relation-diagrams-current-and-proposed-was-Re-Changing-an-article-s-unit-for-subdivision-tp379.html)).
