### ISSUE TITLE
Merge this fork into foodcoops/foodsoft

### ISSUE THREAD

**Issue by wvengen** [foodcoop-adam/foodsoft#163]
This fork has quite diverged from upstream, unfortunately. It's time to merge the features back there, which is also a good opportunity to implement them in a clean(er) way. This is a meta-issue to gather everything that needs to be done, before foodcoops using this fork can transition to upstream.

Minimum required:
- [ ] Revamped member ordering pages [foodsoft-shop](https://github.com/foodcoops/foodsoft-shop) + foodcoops/foodsoft#429
- [ ] Enter group_order_article_quantity in amount and unit (pc / gr switch) - #187
- [x] Screens to work on all closed-but-not-finished orders foodcoops/foodsoft#373
- [x] The use of variables in footer foodcoops/foodsoft#342
- [x] Uploading ods/xls/xlsx spreadsheets foodcoops/foodsoft#361
- [x] Online payments ~~(now integrated with bank accounts?)~~ _(fc-ocnoord, uk request)_ -> [see this branch](https://github.com/wvengen/foodsoft/tree/feature/plugin-mollie), plugin got merged in https://github.com/foodcoops/foodsoft/pull/1031

Figure out how we could do without:
- [ ] Restructured menu, with an admin section (or a foodsoft-shop customization)
- [ ] Signup _(fc-adam, fc-ocnoord)_
- [ ] Shopping-cart functionality (pay to confirm member order) _(fc-ocnoord)_

What is being used but may be omitted or postponed (check with coops):
- [ ] Different price computation models (deposit and tax)
- [ ] Improved financial transactions screen https://github.com/foodcoops/foodsoft/issues/398#issuecomment-176691743
- [ ] Hierarchical categories _(fc-adam)_

What we can omit (because it isn't used anymore):
- Admin can send invitations to multiple members at once
- Check minimum order quantity when closing an order
- Allow to send mail directly to supplier when closing an order
- Multishared plugin: multiple groups
- Maximum order quantity for articles
- Different markup for different groups (used by fc-ocnoord (Jul 2016), implement as plugin later)

**Comment by wvengen** [comment]
I'm experimenting with rewriting the member ordering pages in [React](http://facebook.github.io/react), which makes it all a lot cleaner.

**Comment by wvengen** [comment]
See [foodsoft-shop](https://github.com/foodcoops/foodsoft-shop) repository for revamped member ordering pages in progress.

**Comment by decentral1se** [comment]
Aha, is this still a focus? I just posted http://foodsoft.51229.x6.nabble.com/Status-on-foodcoop-adam-foodsoft-fork-td2748.html and now I see this ;) Well, I am doing a lot of internet stalking on you all :fire:

**Comment by RayOei** [comment]
@wvengen As per the recent zoom discussion: which items of the above list should we transfer to the foodcoops/foodsoft issue list as features to be added upstream?
And any other item you can think of by today's knowledge? 😁

**Comment by wvengen** [comment]
@RayOei I think that https://github.com/foodcoop-adam/foodsoft/issues/187 is the most important (which I would say, depends on https://github.com/foodcoops/foodsoft/pull/1073 which I need to find time to review, to determine the next steps).

If you want the foodcoop-adam member ordering interface, this is implemented in https://github.com/foodcoops/foodsoft-shop and already work with the global hosting (after a bit of setup), except that members cannot click through to it from Foodsoft :( This was meant to be fixed by https://github.com/foodcoops/foodsoft/pull/581 but this proposal was rejected. What may still be accepted, is to not include the Javascript bundle into Foodsoft, but have a config option pointing to where foodsoft-shop is hosted (plain files somewhere, could even be gh-pages).

I think Foodcoop Noord used a feature where members could order, and only have the member orders be included after they were payed. That is not implemented in Foodsoft, and I don't think it will happen soon (it required quite deep changes, that I'm not sure are actually a good idea as it was implemented). I think there are ways to work around this, e.g. set a minimum account balance, so that a first order cannot be too large without initial payment (with online payments using Mollie, these are now available in the global hosting, if I understand it correctly). Note that self-service signup is also not present in upstream Foodsoft. This adds a little extra step in the onboarding process, I'm afraid, but could that be acceptable? This _is_ something that could be accepted into upstream Foodsoft, I think.
